# coding: utf-8

"""
    Kodexa

    Content Intelligence  # noqa: E501

    OpenAPI spec version: 2.0.132
    Contact: suppot@kodexa.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ExceptionReport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'exception_uuid': 'str',
        'message': 'str',
        'platform': 'str'
    }

    attribute_map = {
        'description': 'description',
        'exception_uuid': 'exceptionUuid',
        'message': 'message',
        'platform': 'platform'
    }

    def __init__(self, description=None, exception_uuid=None, message=None, platform=None):  # noqa: E501
        """ExceptionReport - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._exception_uuid = None
        self._message = None
        self._platform = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if exception_uuid is not None:
            self.exception_uuid = exception_uuid
        if message is not None:
            self.message = message
        if platform is not None:
            self.platform = platform

    @property
    def description(self):
        """Gets the description of this ExceptionReport.  # noqa: E501


        :return: The description of this ExceptionReport.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ExceptionReport.


        :param description: The description of this ExceptionReport.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def exception_uuid(self):
        """Gets the exception_uuid of this ExceptionReport.  # noqa: E501


        :return: The exception_uuid of this ExceptionReport.  # noqa: E501
        :rtype: str
        """
        return self._exception_uuid

    @exception_uuid.setter
    def exception_uuid(self, exception_uuid):
        """Sets the exception_uuid of this ExceptionReport.


        :param exception_uuid: The exception_uuid of this ExceptionReport.  # noqa: E501
        :type: str
        """

        self._exception_uuid = exception_uuid

    @property
    def message(self):
        """Gets the message of this ExceptionReport.  # noqa: E501


        :return: The message of this ExceptionReport.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ExceptionReport.


        :param message: The message of this ExceptionReport.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def platform(self):
        """Gets the platform of this ExceptionReport.  # noqa: E501


        :return: The platform of this ExceptionReport.  # noqa: E501
        :rtype: str
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """Sets the platform of this ExceptionReport.


        :param platform: The platform of this ExceptionReport.  # noqa: E501
        :type: str
        """

        self._platform = platform

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExceptionReport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExceptionReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
