name: kodexa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - pytest=4.0.2
  - pytest-runner
  - setuptools=40.5.0
  - conda-build
  - twine=1.10.0
  - pip:
      - requests
      - msgpack
      - texttable
      - addict
      - certifi >= 14.05.14
      - six >= 1.10
      - python_dateutil >= 2.5.3
      - urllib3 >= 1.15.1
