site_name: "Kodexa for Python"

nav:
  - Getting Started: getting-started.md
  - First Steps:
      - Document Basics: documents/first-steps.ipynb
      - Connectors: documents/connectors.md
      - Working with Content: documents/working-with-content.ipynb
      - Selectors: documents/selectors.md
  - Platform Client:
      - Introduction: client/index.md
      - Organizations: client/organizations.ipynb
      - Projects: client/projects.ipynb