site_name: 'platform'

nav:
  - Home: index.md
  - 'Kodexa Document':
      - 'Introduction': kodexa-document/index.md
      - 'Selectors': kodexa-document/selectors.md
  - 'Kodexa Client':
      - 'Introduction': kodexa-client/index.md
      - 'Installation': kodexa-client/installation.md
      - 'Configuration': kodexa-client/configuration.md
      - 'Usage': kodexa-client/usage.md
      - 'API': kodexa-client/api.md

plugins:
  - techdocs-core
  - mkdocstrings