name: Python Package Using Anaconda

on:
  push:
    branches:
      - 'develop'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Increment version
        id: version
        uses: pdodds/Bump-N-Tag-Version@master
        with:
          file_name: './VERSION'
          tag_version: "true"
          postfix: 'beta'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          sudo chmod -R ugo+rwX .
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          yes | mypy --install-types kodexa || true
      - name: Test with pytest
        run: |
          pytest
      - name: Package
        run: |
          python setup.py bdist_wheel sdist
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
