name: Build and deploy documentation

on:
  branches:
    - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up grahpviz
        run: sudo apt-get install graphviz

      - name: Build with xvfb enabled
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: cd docs && mvn -B package

      - name: deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/target/znai